version: '3.8'
services:
  app:
    container_name: final-exam-go-lang-api
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    env_file:
      - .env
    # environment:
      # - DB_CONN="mysql://root:147963@tcp(localhost:3306)/golang_db?charset=utf8mb4&parseTime=True&loc=Local"
    volumes:
      - .:/app
    depends_on:
      - db-mysql
    links:
      - db-mysql          

  db-mysql:
    image: mysql:8.0
    container_name: final-exam-go-lang-db
    restart: always
    env_file:
      - .env
    ports: 
      - 13306:3306
    environment: 
      - MYSQL_ROOT_HOST=localhost 
      - MYSQL_USER=root
      - MYSQL_PASSWORD=147963
      - MYSQL_DATABASE=golang_db
      - MYSQL_ROOT_PASSWORD=147963

